{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/osrf/subt/issues/348/comments/56360506.json"}, "html": {"href": "#!/osrf/subt/issues/348#comment-56360506"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/348.json"}}, "type": "issue", "id": 348, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Sporadic move_base failure in CloudSim: \"Unable to get starting pose of robot, unable to create global plan\""}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2020-02-29T09:17:45.645280+00:00", "user": {"display_name": "Malcolm Stagg", "uuid": "{eee13832-fdd5-4196-aa05-6cfdb1118c65}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D"}, "html": {"href": "https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8c08ab97dc600bddad36e4a58f8cc5afd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMS-3.png"}}, "nickname": "malcolmst7", "type": "user", "account_id": "557058:08ef8b07-1500-4917-989c-89f91ce4beac"}, "updated_on": null, "type": "issue_comment", "id": 56360506}, {"links": {"self": {"href": "data/repositories/osrf/subt/issues/348/comments/56363765.json"}, "html": {"href": "#!/osrf/subt/issues/348#comment-56363765"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/348.json"}}, "type": "issue", "id": 348, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Sporadic move_base failure in CloudSim: \"Unable to get starting pose of robot, unable to create global plan\""}, "content": {"raw": "Update: it appears something weird is going on with timing when this happens. I also see one of my own lookupTransforms failing with an error such as:\n\n```\nLookup would require extrapolation into the past.  Requested time 3960.252000000 but the earliest data is at time 3964.752000000, when looking up transform from frame [X2N1/base_link] to frame [X2N1/artifact_origin]\n```\n\nOn my end I have a StaticTransformBroadcaster which should be publishing the transform necessary for that lookup, along with the published SLAM, so wouldn\u2019t expect it to fail like that \\(the lookup of `3960.252000000` in this case is just from ros::Time\\(0\\) \\).\n\nMaybe this then is related to the TCP buffer overruns in issue #261? I recall it was recommended that all sensor callbacks should be asynchronous to avoid that potential issue, but I ran out of time to complete & test that change before urban circuit. I might just try making that change now to see if that resolves it.", "markup": "markdown", "html": "<p>Update: it appears something weird is going on with timing when this happens. I also see one of my own lookupTransforms failing with an error such as:</p>\n<div class=\"codehilite\"><pre><span></span>Lookup would require extrapolation into the past.  Requested time 3960.252000000 but the earliest data is at time 3964.752000000, when looking up transform from frame [X2N1/base_link] to frame [X2N1/artifact_origin]\n</pre></div>\n\n\n<p>On my end I have a StaticTransformBroadcaster which should be publishing the transform necessary for that lookup, along with the published SLAM, so wouldn\u2019t expect it to fail like that (the lookup of <code>3960.252000000</code> in this case is just from ros::Time(0) ).</p>\n<p>Maybe this then is related to the TCP buffer overruns in issue <a href=\"#!/osrf/subt/issues/261/cloudsim-stops-sending-some-topics\" rel=\"nofollow\" title=\"CloudSim stops sending some topics\" class=\"ap-connect-link\">#261</a>? I recall it was recommended that all sensor callbacks should be asynchronous to avoid that potential issue, but I ran out of time to complete &amp; test that change before urban circuit. I might just try making that change now to see if that resolves it.</p>", "type": "rendered"}, "created_on": "2020-03-01T01:54:20.373504+00:00", "user": {"display_name": "Malcolm Stagg", "uuid": "{eee13832-fdd5-4196-aa05-6cfdb1118c65}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D"}, "html": {"href": "https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8c08ab97dc600bddad36e4a58f8cc5afd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMS-3.png"}}, "nickname": "malcolmst7", "type": "user", "account_id": "557058:08ef8b07-1500-4917-989c-89f91ce4beac"}, "updated_on": "2020-03-01T01:56:31.781269+00:00", "type": "issue_comment", "id": 56363765}, {"links": {"self": {"href": "data/repositories/osrf/subt/issues/348/comments/56368044.json"}, "html": {"href": "#!/osrf/subt/issues/348#comment-56368044"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/348.json"}}, "type": "issue", "id": 348, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Sporadic move_base failure in CloudSim: \"Unable to get starting pose of robot, unable to create global plan\""}, "content": {"raw": "Is this possibly a simulation time limit thing?  That time is definitely over an hour and likely over an hour after you started the run.  On the qualification runs, that\u2019s about when the simulation would stop for me.  Were the actual runs allowed to go over an hour?", "markup": "markdown", "html": "<p>Is this possibly a simulation time limit thing?  That time is definitely over an hour and likely over an hour after you started the run.  On the qualification runs, that\u2019s about when the simulation would stop for me.  Were the actual runs allowed to go over an hour?</p>", "type": "rendered"}, "created_on": "2020-03-01T23:03:18.880430+00:00", "user": {"display_name": "Steven Gray", "uuid": "{7470e809-c304-4b17-b986-685f31fa15c3}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B7470e809-c304-4b17-b986-685f31fa15c3%7D"}, "html": {"href": "https://bitbucket.org/%7B7470e809-c304-4b17-b986-685f31fa15c3%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/e6bee642b76507eb51c2839771722e68d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSG-0.png"}}, "nickname": "stgray", "type": "user", "account_id": "557058:e6cc7c7b-9d1b-4abe-87d5-5f0da7c863e1"}, "updated_on": null, "type": "issue_comment", "id": 56368044}, {"links": {"self": {"href": "data/repositories/osrf/subt/issues/348/comments/56368100.json"}, "html": {"href": "#!/osrf/subt/issues/348#comment-56368100"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/348.json"}}, "type": "issue", "id": 348, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Sporadic move_base failure in CloudSim: \"Unable to get starting pose of robot, unable to create global plan\""}, "content": {"raw": "@{557058:e6cc7c7b-9d1b-4abe-87d5-5f0da7c863e1} The reason why I quoted the late time is because when this happens the text logs get totally filled up with this error message and I lose all the earlier logs. I believe the scoring stops after 60 minutes but the simulation may keep on going for longer - with the urban practice scenarios I think it was about 2 hours or so. I know the issue isn\u2019t just because of the late time though because in these cases the robots have serious behavior issues, often just spinning around in circles or they are completely stopped for the entire simulation, unable to even get to the entrance. \n\nIf I can continue to reproduce this issue, I\u2019m trying to collect some data now to see if topics such as`/clock` are received correctly or are missing a lot of data - that might help to see if it is related to issue #261 .", "markup": "markdown", "html": "<p><span class=\"ap-mention\" data-atlassian-id=\"557058:e6cc7c7b-9d1b-4abe-87d5-5f0da7c863e1\">@Steven Gray</span> The reason why I quoted the late time is because when this happens the text logs get totally filled up with this error message and I lose all the earlier logs. I believe the scoring stops after 60 minutes but the simulation may keep on going for longer - with the urban practice scenarios I think it was about 2 hours or so. I know the issue isn\u2019t just because of the late time though because in these cases the robots have serious behavior issues, often just spinning around in circles or they are completely stopped for the entire simulation, unable to even get to the entrance. </p>\n<p>If I can continue to reproduce this issue, I\u2019m trying to collect some data now to see if topics such as<code>/clock</code> are received correctly or are missing a lot of data - that might help to see if it is related to issue <a href=\"#!/osrf/subt/issues/261/cloudsim-stops-sending-some-topics\" rel=\"nofollow\" title=\"CloudSim stops sending some topics\" class=\"ap-connect-link\">#261</a> .</p>", "type": "rendered"}, "created_on": "2020-03-01T23:15:36.224440+00:00", "user": {"display_name": "Malcolm Stagg", "uuid": "{eee13832-fdd5-4196-aa05-6cfdb1118c65}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D"}, "html": {"href": "https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8c08ab97dc600bddad36e4a58f8cc5afd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMS-3.png"}}, "nickname": "malcolmst7", "type": "user", "account_id": "557058:08ef8b07-1500-4917-989c-89f91ce4beac"}, "updated_on": null, "type": "issue_comment", "id": 56368100}, {"links": {"self": {"href": "data/repositories/osrf/subt/issues/348/comments/56396263.json"}, "html": {"href": "#!/osrf/subt/issues/348#comment-56396263"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/348.json"}}, "type": "issue", "id": 348, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Sporadic move_base failure in CloudSim: \"Unable to get starting pose of robot, unable to create global plan\""}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2020-03-03T19:55:05.365372+00:00", "user": {"display_name": "Malcolm Stagg", "uuid": "{eee13832-fdd5-4196-aa05-6cfdb1118c65}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D"}, "html": {"href": "https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8c08ab97dc600bddad36e4a58f8cc5afd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMS-3.png"}}, "nickname": "malcolmst7", "type": "user", "account_id": "557058:08ef8b07-1500-4917-989c-89f91ce4beac"}, "updated_on": null, "type": "issue_comment", "id": 56396263}], "page": 1, "size": 5}