{"links": {"self": {"href": "data/repositories/osrf/subt/issues/121/comments/53099267.json"}, "html": {"href": "#!/osrf/subt/issues/121#comment-53099267"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/121.json"}}, "type": "issue", "id": 121, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "cloudsim_bridge docker image error on last step"}, "content": {"raw": "Hi Alfredo, \n\nAfter downloading the missing file and running the image I get this error: \n\noverlord@venture:~/cloudsim\\_bridge\\_docker$ ./run.bash cloudsim\\_bridge robotName1:=X1 robotConfig1:=X1\\_SENSOR\\_CONFIG\\_1 robotName2:=X2 robotConfig2:=X2\\_SENSOR\\_CONFIG\\_2  \nxauth:  file /tmp/.docker.xauth does not exist  \nstandard\\_init\\_linux.go:211: exec user process caused \"permission denied\"\n\nAny ideas what could be wrong?", "markup": "markdown", "html": "<p>Hi Alfredo, </p>\n<p>After downloading the missing file and running the image I get this error: </p>\n<p>overlord@venture:~/cloudsim_bridge_docker$ ./run.bash cloudsim_bridge robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1 robotName2:=X2 robotConfig2:=X2_SENSOR_CONFIG_2<br />\nxauth:  file /tmp/.docker.xauth does not exist<br />\nstandard_init_linux.go:211: exec user process caused \"permission denied\"</p>\n<p>Any ideas what could be wrong?</p>", "type": "rendered"}, "created_on": "2019-07-22T21:58:38.927113+00:00", "user": {"display_name": "Hector Escobar", "uuid": "{1c140a49-f2c5-4727-abd9-eb427bfe4253}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B1c140a49-f2c5-4727-abd9-eb427bfe4253%7D"}, "html": {"href": "https://bitbucket.org/%7B1c140a49-f2c5-4727-abd9-eb427bfe4253%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8da90eb0e9b47c9adfc2893e5190483fd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHE-1.png"}}, "nickname": "hector_escobar", "type": "user", "account_id": "5b5b1c941394ae6a72c021df"}, "updated_on": null, "type": "issue_comment", "id": 53099267}