{"links": {"self": {"href": "data/repositories/osrf/subt/pullrequests/104/comments/87878695.json"}, "html": {"href": "#!/osrf/subt/pull-requests/104/_/diff#comment-87878695"}}, "parent": {"id": 87850665, "links": {"self": {"href": "data/repositories/osrf/subt/pullrequests/104/comments/87850665.json"}, "html": {"href": "#!/osrf/subt/pull-requests/104/_/diff#comment-87850665"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 104, "links": {"self": {"href": "data/repositories/osrf/subt/pullrequests/104.json"}, "html": {"href": "#!/osrf/subt/pull-requests/104"}}, "title": "Comms refactor"}, "content": {"raw": "Updated now so that all tests compile and tests for subt-communication packages all pass. However, getting an error on `subt_gazebo` and some other subt packages that this PR does not touch. The `subt_gazebo` error looks like something to do with xacro processing:\n\n\u200c\n\n    Scanning dependencies of target run_tests_subt_gazebo_rostest_test_score.test\n    -- run_tests.py: execute commands\n      /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/catkin_ws/src/jonfink-subt/subt_gazebo --package=subt_gazebo --results-filename test_score.xml --results-base-dir \"/catkin_ws/build/test_results\" /catkin_ws/src/jonfink-subt/subt_gazebo/test/score.test \n    ... logging to /home/developer/.ros/log/rostest-f06f19e61473-18887.log\n    resource not found: husky_description\n    ROS path [0]=/opt/ros/melodic/share/ros\n    ROS path [1]=/catkin_ws/src\n    ROS path [2]=/catkin_ws/install/share\n    ROS path [3]=/opt/ros/melodic/share\n    when processing file: /catkin_ws/src/jonfink-subt/x1_description/urdf/x1.urdf.xacro\n    Traceback (most recent call last):\n      File \"/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest\", line 36, in <module>\n        rostestmain()\n      File \"/opt/ros/melodic/lib/python2.7/dist-packages/rostest/__init__.py\", line 274, in rostestmain\n        _main()\n      File \"/opt/ros/melodic/lib/python2.7/dist-packages/rostest/rostest_main.py\", line 159, in rostestmain\n        testCase = rostest.runner.createUnitTest(pkg, test_file, options.reuse_master, options.clear, options.results_base_dir)\n      File \"/opt/ros/melodic/lib/python2.7/dist-packages/rostest/runner.py\", line 229, in createUnitTest\n        config = roslaunch.parent.load_config_default([test_file], None)\n      File \"/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/config.py\", line 459, in load_config_default\n        raise RLException(e)\n    roslaunch.core.RLException: while processing /catkin_ws/src/jonfink-subt/subt_gazebo/test/launch/test_score.launch:\n    while processing /catkin_ws/src/jonfink-subt/subt_gazebo/test/launch/test_team.launch:\n    while processing /catkin_ws/src/jonfink-subt/x1_gazebo/launch/spawn_x1.launch:\n    while processing /catkin_ws/src/jonfink-subt/x1_control/launch/control.launch:\n    while processing /catkin_ws/src/jonfink-subt/x1_description/launch/description.launch:\n    Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/melodic/lib/xacro/xacro '/catkin_ws/src/jonfink-subt/x1_description/urdf/x1.urdf.xacro'     robot_namespace:=X1     laser_enabled:=false     kinect_enabled:=false     urdf_extras:=     ] returned with code [2]. \n    \n    Param xml is <param command=\"$(find xacro)/xacro '$(find x1_description)/urdf/x1.urdf.xacro'     robot_namespace:=$(arg robot_namespace)     laser_enabled:=$(arg laser_enabled)     kinect_enabled:=$(arg kinect_enabled)     urdf_extras:=$(arg urdf_extras)     \" name=\"robot_description\"/>\n    -- run_tests.py: verify result \"/catkin_ws/build/test_results/subt_gazebo/rostest-test_score.xml\"\n    Cannot find results, writing failure results to '/catkin_ws/build/test_results/subt_gazebo/MISSING-rostest-test_score.xml'", "markup": "markdown", "html": "<p>Updated now so that all tests compile and tests for subt-communication packages all pass. However, getting an error on <code>subt_gazebo</code> and some other subt packages that this PR does not touch. The <code>subt_gazebo</code> error looks like something to do with xacro processing:</p>\n<p>\u200c</p>\n<div class=\"codehilite\"><pre><span></span>Scanning dependencies of target run_tests_subt_gazebo_rostest_test_score.test\n-- run_tests.py: execute commands\n  /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/catkin_ws/src/jonfink-subt/subt_gazebo --package=subt_gazebo --results-filename test_score.xml --results-base-dir &quot;/catkin_ws/build/test_results&quot; /catkin_ws/src/jonfink-subt/subt_gazebo/test/score.test \n... logging to /home/developer/.ros/log/rostest-f06f19e61473-18887.log\nresource not found: husky_description\nROS path [0]=/opt/ros/melodic/share/ros\nROS path [1]=/catkin_ws/src\nROS path [2]=/catkin_ws/install/share\nROS path [3]=/opt/ros/melodic/share\nwhen processing file: /catkin_ws/src/jonfink-subt/x1_description/urdf/x1.urdf.xacro\nTraceback (most recent call last):\n  File &quot;/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest&quot;, line 36, in &lt;module&gt;\n    rostestmain()\n  File &quot;/opt/ros/melodic/lib/python2.7/dist-packages/rostest/__init__.py&quot;, line 274, in rostestmain\n    _main()\n  File &quot;/opt/ros/melodic/lib/python2.7/dist-packages/rostest/rostest_main.py&quot;, line 159, in rostestmain\n    testCase = rostest.runner.createUnitTest(pkg, test_file, options.reuse_master, options.clear, options.results_base_dir)\n  File &quot;/opt/ros/melodic/lib/python2.7/dist-packages/rostest/runner.py&quot;, line 229, in createUnitTest\n    config = roslaunch.parent.load_config_default([test_file], None)\n  File &quot;/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/config.py&quot;, line 459, in load_config_default\n    raise RLException(e)\nroslaunch.core.RLException: while processing /catkin_ws/src/jonfink-subt/subt_gazebo/test/launch/test_score.launch:\nwhile processing /catkin_ws/src/jonfink-subt/subt_gazebo/test/launch/test_team.launch:\nwhile processing /catkin_ws/src/jonfink-subt/x1_gazebo/launch/spawn_x1.launch:\nwhile processing /catkin_ws/src/jonfink-subt/x1_control/launch/control.launch:\nwhile processing /catkin_ws/src/jonfink-subt/x1_description/launch/description.launch:\nInvalid &lt;param&gt; tag: Cannot load command parameter [robot_description]: command [/opt/ros/melodic/lib/xacro/xacro &#39;/catkin_ws/src/jonfink-subt/x1_description/urdf/x1.urdf.xacro&#39;     robot_namespace:=X1     laser_enabled:=false     kinect_enabled:=false     urdf_extras:=     ] returned with code [2].\n\nParam xml is &lt;param command=&quot;$(find xacro)/xacro &#39;$(find x1_description)/urdf/x1.urdf.xacro&#39;     robot_namespace:=$(arg robot_namespace)     laser_enabled:=$(arg laser_enabled)     kinect_enabled:=$(arg kinect_enabled)     urdf_extras:=$(arg urdf_extras)     &quot; name=&quot;robot_description&quot;/&gt;\n-- run_tests.py: verify result &quot;/catkin_ws/build/test_results/subt_gazebo/rostest-test_score.xml&quot;\nCannot find results, writing failure results to &#39;/catkin_ws/build/test_results/subt_gazebo/MISSING-rostest-test_score.xml&#39;\n</pre></div>", "type": "rendered"}, "created_on": "2019-01-13T19:30:53.390070+00:00", "user": {"display_name": "Jon Fink", "uuid": "{89cf7350-7d3a-4a2e-a6ce-43d49bfe9001}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B89cf7350-7d3a-4a2e-a6ce-43d49bfe9001%7D"}, "html": {"href": "https://bitbucket.org/%7B89cf7350-7d3a-4a2e-a6ce-43d49bfe9001%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/d3f96b67926116d5c1121e7dc9a1a8f2d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJF-5.png"}}, "nickname": "jonfink-arl", "type": "user", "account_id": "5b90221dfa38ae2c89609691"}, "updated_on": "2019-01-13T19:30:53.398616+00:00", "type": "pullrequest_comment", "id": 87878695}