{"links": {"self": {"href": "data/repositories/osrf/subt/issues/354/comments/56521788.json"}, "html": {"href": "#!/osrf/subt/issues/354#comment-56521788"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/354.json"}}, "type": "issue", "id": 354, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Is cloudsim totally broken?"}, "content": {"raw": "I\u2019ve been seeing the same thing this week. My last successful run was Monday at 6pm. They are running for a really long time, eventually failing with a server restart, and no logs are available.", "markup": "markdown", "html": "<p>I\u2019ve been seeing the same thing this week. My last successful run was Monday at 6pm. They are running for a really long time, eventually failing with a server restart, and no logs are available.</p>", "type": "rendered"}, "created_on": "2020-03-14T07:29:25.938308+00:00", "user": {"display_name": "Malcolm Stagg", "uuid": "{eee13832-fdd5-4196-aa05-6cfdb1118c65}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D"}, "html": {"href": "https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8c08ab97dc600bddad36e4a58f8cc5afd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMS-3.png"}}, "nickname": "malcolmst7", "type": "user", "account_id": "557058:08ef8b07-1500-4917-989c-89f91ce4beac"}, "updated_on": "2020-03-14T07:32:12.394776+00:00", "type": "issue_comment", "id": 56521788}