{"links": {"self": {"href": "data/repositories/osrf/subt/issues/354/comments/56568759.json"}, "html": {"href": "#!/osrf/subt/issues/354#comment-56568759"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/354.json"}}, "type": "issue", "id": 354, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Is cloudsim totally broken?"}, "content": {"raw": "Those three simulation instances were affected while launching, so there are no logs. I've restarted them.", "markup": "markdown", "html": "<p>Those three simulation instances were affected while launching, so there are no logs. I've restarted them.</p>", "type": "rendered"}, "created_on": "2020-03-18T13:21:23.200959+00:00", "user": {"display_name": "Nate Koenig", "uuid": "{c862cdd9-fcc8-4419-9fc7-e20db14b8fcb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D"}, "html": {"href": "https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:095b1e12-74ed-4e20-b44f-2f0745b616e0/ca24bb11-4787-4b14-a20d-d91835e9bde2/128"}}, "nickname": "Nathan Koenig", "type": "user", "account_id": "557058:095b1e12-74ed-4e20-b44f-2f0745b616e0"}, "updated_on": null, "type": "issue_comment", "id": 56568759}