{"links": {"self": {"href": "data/repositories/osrf/subt/issues/339/comments/56411791.json"}, "html": {"href": "#!/osrf/subt/issues/339#comment-56411791"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/339.json"}}, "type": "issue", "id": 339, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Problems with Cloudsim"}, "content": {"raw": "@{557058:490c665b-b69c-40f3-80ea-64f20747efc4} Thanks for sharing this. I actually see the same thing in 21 out of my 24 runs, along with the error in issue #348.", "markup": "markdown", "html": "<p><span class=\"ap-mention\" data-atlassian-id=\"557058:490c665b-b69c-40f3-80ea-64f20747efc4\">@Martin Dlouhy</span> Thanks for sharing this. I actually see the same thing in 21 out of my 24 runs, along with the error in issue <a href=\"#!/osrf/subt/issues/348/sporadic-move_base-failure-in-cloudsim\" rel=\"nofollow\" title=\"Sporadic move_base failure in CloudSim: &quot;Unable to get starting pose of robot, unable to create global plan&quot;\" class=\"ap-connect-link\">#348</a>.</p>", "type": "rendered"}, "created_on": "2020-03-04T22:13:44.248485+00:00", "user": {"display_name": "Malcolm Stagg", "uuid": "{eee13832-fdd5-4196-aa05-6cfdb1118c65}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D"}, "html": {"href": "https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8c08ab97dc600bddad36e4a58f8cc5afd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMS-3.png"}}, "nickname": "malcolmst7", "type": "user", "account_id": "557058:08ef8b07-1500-4917-989c-89f91ce4beac"}, "updated_on": null, "type": "issue_comment", "id": 56411791}