{"links": {"self": {"href": "data/repositories/osrf/subt/issues/88/comments/52996185.json"}, "html": {"href": "#!/osrf/subt/issues/88#comment-52996185"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/88.json"}}, "type": "issue", "id": 88, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Missing documentation for creating Ignition-compatible docker containers"}, "content": {"raw": "I am currently getting the error \u201cError #3013: Invalid value in field.\u201d whenever trying to submit an image to the Virtual Stix cloudsim.  I have read and followed the instructions here: [#!/osrf/subt/wiki/tutorials/qual\\_cloudsim](#!/osrf/subt/wiki/tutorials/qual_cloudsim) where the image address obtained is the same for both subt\\_docker.bash and subt\\_docker\\_uri.bash calls for being built/referenced so I don\u2019t think it\u2019s a problem with the link.  I also have created an image a few different ways with/without an ENTRYPOINT and I still get the same error so I don\u2019t think it\u2019s a problem with my image.\n\nMy input to the form is as follows:\n\nName: Trial01\n\nCircuit: Virtual Stix\n\nRobot name: alpha\n\nDocker Image URL: <aws stuff>.amazonaws.com/subt/<team\\_name>:<tag>\n\nRobot type: X1 Config 4\n\nI then press \u201cAdd\u201d for the robot, it\u2019s added and shown below then I press \u201cSubmit\u201d and get the \u201cError #3013: Invalid value in field.\u201d  Is it expecting \\(and thus requiring\\) more than one robot?  Is my link bad?  Is this part ready?", "markup": "markdown", "html": "<p>I am currently getting the error \u201cError #3013: Invalid value in field.\u201d whenever trying to submit an image to the Virtual Stix cloudsim.  I have read and followed the instructions here: <a data-is-external-link=\"true\" href=\"#!/osrf/subt/wiki/tutorials/qual_cloudsim\" rel=\"nofollow\">#!/osrf/subt/wiki/tutorials/qual_cloudsim</a> where the image address obtained is the same for both subt_docker.bash and subt_docker_uri.bash calls for being built/referenced so I don\u2019t think it\u2019s a problem with the link.  I also have created an image a few different ways with/without an ENTRYPOINT and I still get the same error so I don\u2019t think it\u2019s a problem with my image.</p>\n<p>My input to the form is as follows:</p>\n<p>Name: Trial01</p>\n<p>Circuit: Virtual Stix</p>\n<p>Robot name: alpha</p>\n<p>Docker Image URL: &lt;aws stuff&gt;.<a href=\"http://amazonaws.com/subt/&lt;team_name&gt;:&lt;tag&gt\" rel=\"nofollow\" class=\"ap-connect-link\">amazonaws.com/subt/&lt;team_name&gt;:&lt;tag&gt</a>;</p>\n<p>Robot type: X1 Config 4</p>\n<p>I then press \u201cAdd\u201d for the robot, it\u2019s added and shown below then I press \u201cSubmit\u201d and get the \u201cError #3013: Invalid value in field.\u201d  Is it expecting (and thus requiring) more than one robot?  Is my link bad?  Is this part ready?</p>", "type": "rendered"}, "created_on": "2019-07-15T21:44:32.876558+00:00", "user": {"display_name": "Arthur Schang", "uuid": "{1403972a-9b64-442b-a69c-d7e9557e1d87}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B1403972a-9b64-442b-a69c-d7e9557e1d87%7D"}, "html": {"href": "https://bitbucket.org/%7B1403972a-9b64-442b-a69c-d7e9557e1d87%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/AS-0.png"}}, "nickname": "Arthur Schang", "type": "user", "account_id": "557058:14b7fd50-d65a-47a8-825c-fa89681d07bd"}, "updated_on": null, "type": "issue_comment", "id": 52996185}