{"links": {"self": {"href": "data/repositories/osrf/subt/issues/120/comments/53270645.json"}, "html": {"href": "#!/osrf/subt/issues/120#comment-53270645"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/120.json"}}, "type": "issue", "id": 120, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Transform from X2_1/base_link/imu_sensor to X2_1/base_link is unavailable"}, "content": {"raw": "Meanwhile the localization works but not always. \n\nAfter startup the connection between `odom` and `X2_1/base_Link` is available:\n\n![](data/bitbucket.org/repo/8ze6Mjd/images/3785758519-Bildschirmfoto_von_2019-08-03_23-26-29.png)\nAfter a few seconds it is not available any more and `odom` is unconnected:\n\n![](data/bitbucket.org/repo/8ze6Mjd/images/3595628376-Bildschirmfoto_von_2019-08-03_23-27-17.png)\nAnd after some more seconds the connection is available again:\n\n![](data/bitbucket.org/repo/8ze6Mjd/images/1980678777-Bildschirmfoto_von_2019-08-03_23-27-59.png)\n\u200c\n\nDoes this have to do with a performance issue? This would explain why the localization is now displaying some valid data as the simulation environment is meanwhile much faster but there are still messages regarding transform problems:\n\n`Transform from X2_1/base_link/imu_sensor to X2_1/base_link was unavailable for the time requested. Using latest instead.`\n\nIs there a problem using robot\\_localization with ignition?", "markup": "markdown", "html": "<p>Meanwhile the localization works but not always. </p>\n<p>After startup the connection between <code>odom</code> and <code>X2_1/base_Link</code> is available:</p>\n<p><img alt=\"\" src=\"data/bitbucket.org/repo/8ze6Mjd/images/3785758519-Bildschirmfoto_von_2019-08-03_23-26-29.png\" />\nAfter a few seconds it is not available any more and <code>odom</code> is unconnected:</p>\n<p><img alt=\"\" src=\"data/bitbucket.org/repo/8ze6Mjd/images/3595628376-Bildschirmfoto_von_2019-08-03_23-27-17.png\" />\nAnd after some more seconds the connection is available again:</p>\n<p><img alt=\"\" src=\"data/bitbucket.org/repo/8ze6Mjd/images/1980678777-Bildschirmfoto_von_2019-08-03_23-27-59.png\" />\n\u200c</p>\n<p>Does this have to do with a performance issue? This would explain why the localization is now displaying some valid data as the simulation environment is meanwhile much faster but there are still messages regarding transform problems:</p>\n<p><code>Transform from X2_1/base_link/imu_sensor to X2_1/base_link was unavailable for the time requested. Using latest instead.</code></p>\n<p>Is there a problem using robot_localization with ignition?</p>", "type": "rendered"}, "created_on": "2019-08-03T21:40:25.238896+00:00", "user": {"display_name": "Sophisticated Engineering", "uuid": "{12ed2357-e253-4c67-a2b9-7e12c64773e4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D"}, "html": {"href": "https://bitbucket.org/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/2a19963da6b0f34b3be28d8690bdd711d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSE-6.png"}}, "nickname": "sopheng", "type": "user", "account_id": "5c0d82b3128c7106f57691a7"}, "updated_on": null, "type": "issue_comment", "id": 53270645}