{"links": {"self": {"href": "data/repositories/osrf/subt/issues/300/comments/56683351.json"}, "html": {"href": "#!/osrf/subt/issues/300#comment-56683351"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/300.json"}}, "type": "issue", "id": 300, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Running into \"max depth exceeded\" error with the current subt-virtual-testbed base image"}, "content": {"raw": "This appears to be resolved now in the new image versions", "markup": "markdown", "html": "<p>This appears to be resolved now in the new image versions</p>", "type": "rendered"}, "created_on": "2020-03-27T03:37:20.586426+00:00", "user": {"display_name": "Malcolm Stagg", "uuid": "{eee13832-fdd5-4196-aa05-6cfdb1118c65}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D"}, "html": {"href": "https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8c08ab97dc600bddad36e4a58f8cc5afd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMS-3.png"}}, "nickname": "malcolmst7", "type": "user", "account_id": "557058:08ef8b07-1500-4917-989c-89f91ce4beac"}, "updated_on": null, "type": "issue_comment", "id": 56683351}