{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "links": {"attachments": {"href": "data/repositories/osrf/subt/issues/155/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/subt/issues/155.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/155/watch"}, "comments": {"href": "data/repositories/osrf/subt/issues/155/comments_page=1.json"}, "html": {"href": "#!/osrf/subt/issues/155/performance-issue-every-2-seconds"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/155/vote"}}, "reporter": {"display_name": "Sophisticated Engineering", "uuid": "{12ed2357-e253-4c67-a2b9-7e12c64773e4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D"}, "html": {"href": "https://bitbucket.org/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/2a19963da6b0f34b3be28d8690bdd711d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSE-6.png"}}, "nickname": "sopheng", "type": "user", "account_id": "5c0d82b3128c7106f57691a7"}, "title": "Performance issue every 2 seconds", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Running the robot localization every 2 seconds problems are logged with the message:\r\n\r\n\u201cTransform from X2\\_1/base\\_link/imu\\_sensor to X2\\_1 was unavailable for the time requested. Using latest instead.\u201d\r\n\r\nThe calculations of this node are done 50 time per second and only exactly every 2 seconds this error occurs. So there seems to be a process that is using much time every 2 seconds that leads to these errors.\r\n\r\nThe attached log shows this 2-second period. \\(It was created during a run with debug parameter set.\\)\r\n\r\nSuch messages do not show up in the Gazebo Version only in Ignition. So there seems to be a problem.", "markup": "markdown", "html": "<p>Running the robot localization every 2 seconds problems are logged with the message:</p>\n<p>\u201cTransform from X2_1/base_link/imu_sensor to X2_1 was unavailable for the time requested. Using latest instead.\u201d</p>\n<p>The calculations of this node are done 50 time per second and only exactly every 2 seconds this error occurs. So there seems to be a process that is using much time every 2 seconds that leads to these errors.</p>\n<p>The attached log shows this 2-second period. (It was created during a run with debug parameter set.)</p>\n<p>Such messages do not show up in the Gazebo Version only in Ignition. So there seems to be a problem.</p>", "type": "rendered"}, "assignee": {"display_name": "Addisu Z. Taddese", "uuid": "{9d7fdc68-d270-4080-bf03-4df0d0dbf635}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B9d7fdc68-d270-4080-bf03-4df0d0dbf635%7D"}, "html": {"href": "https://bitbucket.org/%7B9d7fdc68-d270-4080-bf03-4df0d0dbf635%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:90bc87b0-2886-4377-a17c-3a6629a697ff/afbf9be5-1e4c-4810-89d4-e58831f34b11/128"}}, "nickname": "azeey", "type": "user", "account_id": "557058:90bc87b0-2886-4377-a17c-3a6629a697ff"}, "state": "closed", "version": null, "edited_on": null, "created_on": "2019-08-10T21:59:07.557390+00:00", "milestone": null, "updated_on": "2019-10-31T05:57:25.094136+00:00", "type": "issue", "id": 155}