{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "links": {"attachments": {"href": "data/repositories/osrf/subt/issues/266/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/subt/issues/266.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/266/watch"}, "comments": {"href": "data/repositories/osrf/subt/issues/266/comments_page=1.json"}, "html": {"href": "#!/osrf/subt/issues/266/issue-with-zlib"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/266/vote"}}, "reporter": {"display_name": "Chris Fotache", "uuid": "{cd3b9ed2-9a40-452b-ab2c-331d13096957}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd3b9ed2-9a40-452b-ab2c-331d13096957%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd3b9ed2-9a40-452b-ab2c-331d13096957%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/40ac88759cdee5d3abe8a21f3374c697d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCF-1.png"}}, "nickname": "chrisfotache", "type": "user", "account_id": "5c93ca4876fb272e06b54f6c"}, "title": "Issue with Zlib", "component": null, "votes": 0, "watches": 1, "content": {"raw": "I just installed Cartographer\u2026 that messed up Protobuf \\(changed version\\) so I couldn\u2019t build anything anymore.\r\n\r\nI was able to restore Protobuf to its initial version \\(3.0.0\\), and now the main simulation builds, but I can\u2019t build our own program, which was working fine before all this. The error is below. I even got your sample subt\\_solution code, and it\u2019s the exact same error:\r\n\r\n\\[100%\\] Linking CXX executable /home/---/subt\\_solution/devel/lib/subt\\_seed/subt\\_seed\\_node  \r\n/usr/bin/ld: cannot find -lZLIB::ZLIB  \r\ncollect2: error: ld returned 1 exit status  \r\nsubt\\_seed/CMakeFiles/subt\\_seed\\_node.dir/build.make:126: recipe for target '/home/---/subt\\_solution/devel/lib/subt\\_seed/subt\\_seed\\_node' failed  \r\nmake\\[2\\]: \\*\\*\\* \\[/home/---/subt\\_solution/devel/lib/subt\\_seed/subt\\_seed\\_node\\] Error 1  \r\nCMakeFiles/Makefile2:929: recipe for target 'subt\\_seed/CMakeFiles/subt\\_seed\\_node.dir/all' failed  \r\nmake\\[1\\]: \\*\\*\\* \\[subt\\_seed/CMakeFiles/subt\\_seed\\_node.dir/all\\] Error 2  \r\nMakefile:140: recipe for target 'all' failed  \r\nmake: \\*\\*\\* \\[all\\] Error 2  \r\nInvoking \"make install -j24 -l24\" failed\r\n\r\nAny suggestions?\u2026.\r\n\r\n\u200c", "markup": "markdown", "html": "<p>I just installed Cartographer\u2026 that messed up Protobuf (changed version) so I couldn\u2019t build anything anymore.</p>\n<p>I was able to restore Protobuf to its initial version (3.0.0), and now the main simulation builds, but I can\u2019t build our own program, which was working fine before all this. The error is below. I even got your sample subt_solution code, and it\u2019s the exact same error:</p>\n<p>[100%] Linking CXX executable /home/---/subt_solution/devel/lib/subt_seed/subt_seed_node<br />\n/usr/bin/ld: cannot find -lZLIB::ZLIB<br />\ncollect2: error: ld returned 1 exit status<br />\nsubt_seed/CMakeFiles/subt_seed_node.dir/build.make:126: recipe for target '/home/---/subt_solution/devel/lib/subt_seed/subt_seed_node' failed<br />\nmake[2]: *** [/home/---/subt_solution/devel/lib/subt_seed/subt_seed_node] Error 1<br />\nCMakeFiles/Makefile2:929: recipe for target 'subt_seed/CMakeFiles/subt_seed_node.dir/all' failed<br />\nmake[1]: *** [subt_seed/CMakeFiles/subt_seed_node.dir/all] Error 2<br />\nMakefile:140: recipe for target 'all' failed<br />\nmake: *** [all] Error 2<br />\nInvoking \"make install -j24 -l24\" failed</p>\n<p>Any suggestions?\u2026.</p>\n<p>\u200c</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2019-11-07T04:40:04.037970+00:00", "milestone": null, "updated_on": "2020-02-21T21:48:56.980603+00:00", "type": "issue", "id": 266}