{"priority": "major", "kind": "proposal", "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "links": {"attachments": {"href": "data/repositories/osrf/subt/issues/291/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/subt/issues/291.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/291/watch"}, "comments": {"href": "data/repositories/osrf/subt/issues/291/comments_page=1.json"}, "html": {"href": "#!/osrf/subt/issues/291/having-trouble-while-running-the"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/291/vote"}}, "reporter": {"display_name": "baila", "uuid": "{22c52b82-0467-49e5-afbf-803525a87d06}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B22c52b82-0467-49e5-afbf-803525a87d06%7D"}, "html": {"href": "https://bitbucket.org/%7B22c52b82-0467-49e5-afbf-803525a87d06%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/e82780891a1e938f0bf3a529adc858a5d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsB-3.png"}}, "nickname": "baila", "type": "user", "account_id": "557058:42fc2023-4935-4b2e-8079-075649866124"}, "title": "Having trouble while running the subt_testbed", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Hi all,\r\n\r\nI am trying to run the urban circuit simulation via below command, while getting the error.\r\n\r\n`baila@baila:~/subt_testbed$ ./run.bash osrf/subt-virtual-testbed tunnel_circuit_practice.ign worldName:=tunnel_circuit_practice_01 robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1`  \r\n`docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused \"exec: \"tunnel_circuit_practice.ign\": executable file not found in $PATH\": unknown.`  \r\n`baila@baila:~/subt_testbed$`\r\n\r\nAny clue what to do here? What I did different was, I saved the image on different computer\\(due to network issues in my development setup\\) and imported on this machine. But after importing, while trying to run, got this error.\r\n\r\n\u200c\r\n\r\nAny help other than doing this from beginning for my development setup?", "markup": "markdown", "html": "<p>Hi all,</p>\n<p>I am trying to run the urban circuit simulation via below command, while getting the error.</p>\n<p><code>baila@baila:~/subt_testbed$ ./run.bash osrf/subt-virtual-testbed tunnel_circuit_practice.ign worldName:=tunnel_circuit_practice_01 robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1</code><br />\n<code>docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused \"exec: \"tunnel_circuit_practice.ign\": executable file not found in $PATH\": unknown.</code><br />\n<code>baila@baila:~/subt_testbed$</code></p>\n<p>Any clue what to do here? What I did different was, I saved the image on different computer(due to network issues in my development setup) and imported on this machine. But after importing, while trying to run, got this error.</p>\n<p>\u200c</p>\n<p>Any help other than doing this from beginning for my development setup?</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2019-12-09T16:34:57.317078+00:00", "milestone": null, "updated_on": "2019-12-16T14:23:33.420144+00:00", "type": "issue", "id": 291}