{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "links": {"attachments": {"href": "data/repositories/osrf/subt/issues/96/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/subt/issues/96.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/96/watch"}, "comments": {"href": "data/repositories/osrf/subt/issues/96/comments_page=1.json"}, "html": {"href": "#!/osrf/subt/issues/96/having-trouble-with-nvidia-driver"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/96/vote"}}, "reporter": {"display_name": "baila", "uuid": "{22c52b82-0467-49e5-afbf-803525a87d06}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B22c52b82-0467-49e5-afbf-803525a87d06%7D"}, "html": {"href": "https://bitbucket.org/%7B22c52b82-0467-49e5-afbf-803525a87d06%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/e82780891a1e938f0bf3a529adc858a5d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsB-3.png"}}, "nickname": "baila", "type": "user", "account_id": "557058:42fc2023-4935-4b2e-8079-075649866124"}, "title": "Having trouble with nvidia driver", "component": null, "votes": 1, "watches": 1, "content": {"raw": "Hey all,\r\n\r\nAfter trying to rectify the errors several times, I tried to do the whole docker setup from the beginning. I am at the stage of \r\n\r\n`docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi`\r\n\r\nAll the layers downloaded and extracted properly. But got the below error like,\r\n\r\n`baila@baila-PC:~$ docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi`  \r\n`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \"process_linux.go:413: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 --pid=3101 /var/lib/docker/overlay2/eedc1522da24fb7971e5ce9676212a4ce2dbe1469edc5dfecd108a12406b1155/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"\": unknown.`  \r\n`baila@baila-PC:~$`\r\n\r\nI tried to follow the next steps of troubleshooting, seems\r\n\r\n`baila@baila-PC:~$ sudo apt-get install nvidia-384`\r\n\r\n`[sudo] password for baila: `\r\n\r\n`Reading package lists... Done`\r\n\r\n`Building dependency tree       `\r\n\r\n`Reading state information... Done`\r\n\r\n`nvidia-384 is already the newest version (390.116-0ubuntu0.18.04.1).`\r\n\r\n`0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.`\r\n\r\n`baila@baila-PC:~$`\r\n\r\n\u200c\r\n\r\nAny help how to fix the problem? I have the below nvidia driver in use,\r\n\r\n![](data/bitbucket.org/repo/8ze6Mjd/images/1143197203-graphics_driver.png)\r\nMy questions are,\r\n\r\n1. Will it work?\r\n2. Can I continue further if the problem couldn\u2019t be resolved?\r\n\r\nPlease help me, I am stuck badly.", "markup": "markdown", "html": "<p>Hey all,</p>\n<p>After trying to rectify the errors several times, I tried to do the whole docker setup from the beginning. I am at the stage of </p>\n<p><code>docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi</code></p>\n<p>All the layers downloaded and extracted properly. But got the below error like,</p>\n<p><code>baila@baila-PC:~$ docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi</code><br />\n<code>docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \"process_linux.go:413: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda&gt;=10.1 brand=tesla,driver&gt;=384,driver&lt;385 brand=tesla,driver&gt;=396,driver&lt;397 brand=tesla,driver&gt;=410,driver&lt;411 --pid=3101 /var/lib/docker/overlay2/eedc1522da24fb7971e5ce9676212a4ce2dbe1469edc5dfecd108a12406b1155/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"\": unknown.</code><br />\n<code>baila@baila-PC:~$</code></p>\n<p>I tried to follow the next steps of troubleshooting, seems</p>\n<p><code>baila@baila-PC:~$ sudo apt-get install nvidia-384</code></p>\n<p><code>[sudo] password for baila:</code></p>\n<p><code>Reading package lists... Done</code></p>\n<p><code>Building dependency tree</code></p>\n<p><code>Reading state information... Done</code></p>\n<p><code>nvidia-384 is already the newest version (390.116-0ubuntu0.18.04.1).</code></p>\n<p><code>0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.</code></p>\n<p><code>baila@baila-PC:~$</code></p>\n<p>\u200c</p>\n<p>Any help how to fix the problem? I have the below nvidia driver in use,</p>\n<p><img alt=\"\" src=\"data/bitbucket.org/repo/8ze6Mjd/images/1143197203-graphics_driver.png\" />\nMy questions are,</p>\n<ol>\n<li>Will it work?</li>\n<li>Can I continue further if the problem couldn\u2019t be resolved?</li>\n</ol>\n<p>Please help me, I am stuck badly.</p>", "type": "rendered"}, "assignee": {"display_name": "Nate Koenig", "uuid": "{c862cdd9-fcc8-4419-9fc7-e20db14b8fcb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D"}, "html": {"href": "https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:095b1e12-74ed-4e20-b44f-2f0745b616e0/ca24bb11-4787-4b14-a20d-d91835e9bde2/128"}}, "nickname": "Nathan Koenig", "type": "user", "account_id": "557058:095b1e12-74ed-4e20-b44f-2f0745b616e0"}, "state": "closed", "version": null, "edited_on": null, "created_on": "2019-07-03T13:30:33.599022+00:00", "milestone": null, "updated_on": "2019-10-31T06:02:33.419030+00:00", "type": "issue", "id": 96}